dist: xenial
sudo: required
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends libfuse-dev libflac++-dev libvorbis-dev libmp3lame-dev libid3tag0-dev asciidoc xmlto libsox-dev libchromaprint-dev python3-mutagen
script: ./autogen.sh && ./configure && make && make check
